INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('DM04', '서대문구청 푸른도시과', '02-330-1714');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('DM05', '서대문구청 청소행정과', '02-330-1518');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('EARD', '서울특별시 동부도로사업소', '02-2040-0368');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('EP45', '은평구청 전산정보과', '02-351-6383');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('EP71', '은평구청 공원녹지과', '02-351-8007');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('EP92', '은평구청 자원순환과', '02-351-7561');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('G055', '자치행정과', '02-330-1080');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('G111', '교통관리과', '02-330-1595');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('G271', '푸른도시과', '02-330-1708');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('G382', '교통행정과', '02-330-1595');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('GA00', '관악구청', '02-879-5831');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('GB01', '강북구청 공원녹지과', '02-901-6925');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('GC02', '금천구청 U-통합운영센터', '02-2627-1904');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('GJ00', '서울특별시 광진구청', '02-450-5100');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('GN71', '강남구청 공원녹지과', '02-3423-6248');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('GR00', '구로구청', '02-860-2114');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('GS71', '강서구청 공원녹지과', '02-2600-4112');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('GSRD', '서울특별시 강서도로사업소', '02-2657-7961');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('JG00', '중구청', '02-3396-5855');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('JR00', '서울특별시 중랑구청', '02-2094-0594');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('NORD', '서울특별시 북부도로사업소', '02-944-5470');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('SC00', '서초구청', '02-2155-6091');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('SD00', '성동구청', '02-2286-5875');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('SDRD', '서울특별시 성동도로사업소', '02-2210-1547');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('SORD', '서울특별시 남부도로사업소', '02-3284-5456');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('SP03', '송파구청 안전담당관', '02-2147-3090');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('WERD', '서울특별시 서부도로사업소', '02-300-8394');
INSERT INTO `bell_admin_tb` (`be_admin_code`, `be_admin_name`, `be_admin_tel`) VALUES ('YC00', '양천구청', '02-2620-4793');
