INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('DB00', '서울특별시 도봉구청', '02-2091-4273');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('DD00', '서울특별시 동대문구청', '02-2127-4084');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('DJ00', '서울특별시동작구청', '02-820-2906');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('DM00', '서울특별시 서대문구청', '02-330-1080');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('EP00', '서울특별시 은평구청', '02-351-8007');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('GB00', '서울특별시 강북구청', '02-901-7266');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('GB01', '서울특별시 강북경찰서', '02-901-7266');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('GC00', '서울특별시 금천구청', '02-2627-1910');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('GD00', '서울특별시 강동구청', '02-3425-7090');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('GJ00', '서울특별시 광진구청', '02-450-7678');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('GN00', '서울특별시 강남구청', '02-3423-6772');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('GR00', '서울특별시 구로구청', '02-860-2114');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('GS00', '서울특별시 강서구청', '02-2600-1884');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG00', '서울특별시 중구', '02-3396-4744');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG01', '서울특별시 중구시설관리공단 충무스포츠센터', '02-2280-8400');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG02', '서울특별시 중구시설관리공단 회현체육센터', '02-2280-8430');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG03', '서울특별시 중구시설관리공단 훈련원공원종합체육관', '02-2280-8398');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG04', '서울특별시 중구시설관리공단 장충문화체육센터', '02-2280-8466');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG05', '서울특별시 중구시설관리공단 무학봉체육관', '02-2280-8426');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG06', '서울특별시 중구시설관리공단 가온도서관', '02-2280-8470');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG07', '서울특별시 중구시설관리공단 남산타운문화체육센터', '02-2280-8484');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG08', '서울특별시 중구시설관리공단 손기정문화체육센터', '02-2280-8450');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG09', '서울특별시 중구시설관리공단 어울림도서관', '02-2280-8490');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG10', '서울특별시 중구시설관리공단 중구구민회관', '02-2280-8388');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG11', '서울특별시 중구시설관리공단 중구종합복지센터', '02-2280-8315');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG12', '서울특별시 중구청 충현공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG13', '서울특별시 중구청 초동공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG14', '서울특별시 중구청 신당사거리공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG15', '서울특별시 중구청 성광공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG16', '서울특별시 중구청 약수동공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG17', '서울특별시 중구청 문화공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG18', '서울특별시 중구청 필동공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG19', '서울특별시 중구청 다산동공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG20', '서울특별시 중구청 청구공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG21', '서울특별시 중구청 버티공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG22', '서울특별시 중구청 신당역공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG23', '서울특별시 중구청 장충공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG24', '서울특별시 중구청 손기정공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG25', '서울특별시 중구청 동산공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG26', '서울특별시 중구청 남산동공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG27', '서울특별시 중구청 새싹마을공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG28', '서울특별시 중구청 묵정공원공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG29', '서울특별시 중구청 다산아트공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG30', '서울특별시 중구청 황학어린이공원공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG31', '서울특별시 중구청 구민회관부설주차장', '02-2265-7765');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JG32', '서울특별시 중구청 진양인공도로노상공영주차장', '02-2280-8360');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JN00', '서울특별시 종로구청', '02-2148-4301');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('JR00', '서울특별시 중랑구청', '02-2094-0284');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('MP00', '서울특별시 마포구청', '02-3153-8432');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('NW00', '서울특별시 노원구청', '02-2116-4917');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('SB00', '서울특별시 성북구청', '02-2241-4562');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('SC00', '서울특별시_서초구', '02-2155-6091');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('SD00', '서울특별시 성동구청', '02-2286-5879');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('SE00', '서울특별시 시청', '02-2100-5397');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('SE71', '서울특별시시설관리공단', '02-2290-6449');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('SP00', '서울특별시 송파구청', '02-2147-3112');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('YC00', '서울특별시 양천구청', '02-2620-4793');
INSERT INTO `cctv_admin_tb` (`cc_admin_code`, `cc_admin_name`, `cc_admin_tel`) VALUES ('YD00', '서울특별시 영등포구', '02-2670-4069');
